### ISSUE TITLE
Refactor backend filtering of transactions

### ISSUE THREAD

**Issue by clen678** [Taks0708/SOFTENG310-FinTrack#106]
The way the transaction is up is that it only sends 10 transactions at a time. So that means in in the frontend we fetch these transactions then apply the desired filter, those 10 transactions per page will be reduced down to anything less than 10. Meaning we will get less than 10 transactions per page. 

We need to use ALL transactions instead of transactions by page to fetch. We also want to reverse the order of the transactions log. But because we only get 10 transactions at a time if we want to reverse the order at any level above the backend, we can only reverse the order of the provided 10 (this is not reversing the order of all the transactions, instead its just reversing the order per 10 transactions).

**Comment by vonner04** [comment]
Agreed, seems to be a pretty aids functionality.
