### ISSUE TITLE
Sign out button

### ISSUE THREAD

**Issue by Taks07** [Taks0708/SOFTENG310-FinTrack#120]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to sign out any time since there currently isnt a way to do that manually. This would be useful for users that want multiple accounts, or even just for testing purposes.

**Describe the solution you'd like**
Just have a log off button in the header, that when clicked, will remove the auth token. This should effectively log the user off.

**Describe alternatives you've considered**
Users can currently just go directly to the login/signup page by editing the url, but this isnt very user-friendly

**Additional context**
None

**Comment by fayzanrj** [comment]
Hey! I’m new to open source and would love to implement this feature. Could you please assign it to me?
