### ISSUE TITLE
Ability to view transaction title

### ISSUE THREAD

**Issue by Ben-G-Man** [Taks0708/SOFTENG310-FinTrack#139]
**Is your feature request related to a problem? Please describe.**
There is currently no way to view a transaction's title once it has been submitted.

**Describe the solution you'd like**
I would like to be able to see the transaction title in the list view and then have this expand out to reveal further information such as the transaction description.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tom1dev** [comment]
Douplicate issue of #129
