### ISSUE TITLE
Display total number of pages in home page

### ISSUE THREAD

**Issue by Ben-G-Man** [Taks0708/SOFTENG310-FinTrack#144]
**Is your feature request related to a problem? Please describe.**
Currently there is no indication of how many pages of transactions exist in total in the home page.

**Describe the solution you'd like**
Rather than `leftLink {currentPage} rightLink` the home page should display `leftLink {currentPage} "of" {totalPages} rightLink` .

**Comment by chrisv09** [comment]
I used forward slash, but it is done
