### ISSUE TITLE
Add transaction log button functionality 

### ISSUE THREAD

**Issue by Taks07** [Taks0708/SOFTENG310-FinTrack#39]
![image](https://github.com/user-attachments/assets/01d434fa-4cb2-487f-a3a2-3294c5541c6a)

Add the functionality of adding/deleting transactions to the buttons from #36

Depends on #36 and #34

**Comment by clen678** [comment]
Does this open up a form to add a transaction?

**Comment by vonner04** [comment]
**Tasks:** 

- Reflect changes from adding and deleting transaction to transaction log component. (Backend?)
- UI for adding and delete transaction interface. (component?)
- UI for transactions appearing in transaction log component. (component?)

I think this task can be split into 3 like this if that makes it easier to work with.

**Comment by vonner04** [comment]
This is done. https://github.com/Taks0708/SOFTENG310-FinTrack/pull/93
