### ISSUE TITLE
Create dashboard

### ISSUE THREAD

**Issue by Taks07** [Taks0708/SOFTENG310-FinTrack#43]
![image](https://github.com/user-attachments/assets/5c127398-4fab-481e-9e24-244f314be4dd)
![image](https://github.com/user-attachments/assets/e84e0605-f26e-41ad-ae37-da629e913b9a)

Put together all the components to make the dashboard. Depends on all dashboard components

**Comment by vonner04** [comment]
Just need financial metrics and header now.

**Comment by vonner04** [comment]
UPDATE: Just missing financial metrics.

**Comment by Taks07** [comment]
Pretty much completed by the financial metrics being finished. i.e. closed by #111
